cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    test2:
      logged_in: false
      name: test1
      password: $2b$12$dk4odyG5RaskzWjPu8tTM.jtyEhzWa6ebWb49E5YIAm0hyhzpGPNq
    teto:
      logged_in: false
      name: Marina
      password: $2b$12$dk4odyG5RaskzWjPu8tTM.jtyEhzWa6ebWb49E5YIAm0hyhzpGPNq
